### ISSUE TITLE
右上角connect wallet

### ISSUE THREAD

**Issue by Erreth-Akbe** [SparkNFT/SparkLink#10]
右上角两个button距离过近，位置应该做垂直居中处理，样式都有阴影

**Comment by Geoffreyyy** [comment]
![image](https://user-images.githubusercontent.com/92965123/140600074-37c86124-d6f7-470c-84d8-4b099b19d8e4.png)
鼠标移上去会显示黑色一大块，修改成只点击 need help 按钮

**Comment by Geoffreyyy** [comment]
![image](https://user-images.githubusercontent.com/92965123/140600099-315f255c-67eb-4466-be33-5fafcf869ba5.png)
社交媒体去掉 只保留下面LOGO @yuhuison

**Comment by Geoffreyyy** [comment]
![image](https://user-images.githubusercontent.com/92965123/140600109-08d3a774-a0cb-4169-b503-239740e1d0fc.png)
这部分向右移动，和上面的资源字段并齐

**Comment by Geoffreyyy** [comment]
所有中文字段里面的标点用中文的，英文的用英文。****** @yuhuison
