### ISSUE TITLE
pls change the medium icon jump link to a new URL:https://medium.com/@SparkLink_Protocol

### ISSUE THREAD

**Issue by Geoffreyyy** [SparkNFT/SparkLink#113]

**Comment by Geoffreyyy** [comment]
URL:https://medium.com/@SparkLink_Protocol 
![image](https://user-images.githubusercontent.com/92965123/167368868-6af5fd4b-ccf9-49a9-a5d2-5560d549af6a.png)
this one

**Comment by Geoffreyyy** [comment]
@codeAtNow

**Comment by SantanaSP** [comment]
Please follow one of our issue templates when you open a new issue. Reopen this when you rewrite it.
