### ISSUE TITLE
collection page 中文/english

### ISSUE THREAD

**Issue by Geoffreyyy** [SparkNFT/SparkLink#114]

**Comment by Geoffreyyy** [comment]
those sentences need in chinese if the page language in chinese

![image](https://user-images.githubusercontent.com/92965123/167417152-f76b7a31-f609-4c52-b8a2-1b420d56f2f3.png)


下级节点抽成比例

作品是否加密

**Comment by Geoffreyyy** [comment]
## Replace the *ture* or *false* displayed in the front end with *yes* or *no*

**Comment by codeAtNow** [comment]
Add PR #119

**Comment by SantanaSP** [comment]
What did you mean "Collection Page"? Did you mean Art page, Spark page, or both?
