### ISSUE TITLE
Customer need the tap bar display correct site's name.

### ISSUE THREAD

**Issue by Erreth-Akbe** [SparkNFT/SparkLink#117]
## What's going wrong?

![image](https://user-images.githubusercontent.com/43749085/167451310-745fcb9d-ccd4-4aa1-bd62-c8914c67024c.png)

## How to reproduce?
None.
## Expected behavior

display `SparkLink` is OK.

## Context

refactor.

**Comment by Geoffreyyy** [comment]
![image](https://user-images.githubusercontent.com/92965123/167541897-646a65d6-b5f0-41a0-aa9a-ea95929ac023.png)
## change this logo to new one pls
![4](https://user-images.githubusercontent.com/92965123/167542079-0a6fb44f-5fae-4189-a51d-b1596668dc39.png)
