### ISSUE TITLE
Royalty Price need be checked whether it is in the required field

### ISSUE THREAD

**Issue by Geoffreyyy** [SparkNFT/SparkLink#141]
## Summary

Is your feature request related to a problem? Please describe.

![image](https://user-images.githubusercontent.com/92965123/169062173-fd21e3fb-8a85-47de-b2b2-1fd237725db2.png)
If the user does not fill in this option, the user cannot publish. This area needs to be marked as a required field

## Expected Behaviour

Use checkboxes to record goals.

## Solution

If the user does not fill in this option, the user cannot publish. This area needs to be marked as a required field

### Alternative

Mark as mandatory
![image](https://user-images.githubusercontent.com/92965123/169062970-5feb25fc-bc0a-465b-96ed-bc171170e995.png)

## Roadmap

Maintainer could use this section to record issue roadmap.

**Comment by Geoffreyyy** [comment]
If the user does not fill in this option, the user cannot publish.
![image](https://user-images.githubusercontent.com/92965123/169064635-2b982832-8922-43b2-a243-a0edaa6677dc.png)

**Comment by SantanaSP** [comment]
I'll take over it.
