### ISSUE TITLE
暂时置灰还未上线的主网选项

### ISSUE THREAD

**Issue by Geoffreyyy** [SparkNFT/SparkLink#148]
## Summary

置灰还未上线的主网选择按钮，无法点击
![image](https://user-images.githubusercontent.com/92965123/169326226-bf6d2495-b804-4f56-af66-38f7f0609043.png)

## Expected Behaviour

还未上线前，用户容易点击操作而造成无法发布的疑惑

## Solution

先置灰eth and bsc，等上线后依次复原。目前阶段只保留rinkeby和matic

### Alternative

Describe alternatives you've considered

## Roadmap

Maintainer could use this section to record issue roadmap.

**Comment by SantanaSP** [comment]
Keep using English please.
