### ISSUE TITLE
the email box button got bug

### ISSUE THREAD

**Issue by Geoffreyyy** [SparkNFT/SparkLink#155]
## What's going wrong?

![image](https://user-images.githubusercontent.com/92965123/169701095-2ec4e460-7d8a-4cf0-8d82-654c914cc525.png)

check here, the text out of the button 

## How to reproduce?

Go to check the email box and the button

## Expected behavior

please keep the "contact us" in the button box

## Context

Which branch / version this issue exists on, and other context information.

**Comment by Geoffreyyy** [comment]
。

**Comment by wangshiy** [comment]
link to this pr: https://github.com/SparkNFT/SparkLink/pull/185

**Comment by SantanaSP** [comment]
Fixed by #185 .
