### ISSUE TITLE
Class or terminology description

### ISSUE THREAD

**Issue by Geoffreyyy** [SparkNFT/SparkLink#160]
## Summary
Class or terminology description in every function part

## Expected Behaviour

Class or terminology description 

## Solution

Describe the solution you'd like.
If you have no idea pls just leave it blank.

### Alternative

Describe alternatives you've considered

## Roadmap

Maintainer could use this section to record issue roadmap.

**Comment by Geoffreyyy** [comment]
A description of the corresponding class of the project or function, and a description of any related terms used during development, for more friendly?

**Comment by SantanaSP** [comment]
I don't think its useful to developers since our project js a quite simple frontend project and do not have many glossaries. What do you think?

**Comment by Geoffreyyy** [comment]
> I don't think its useful to developers since our project js a quite simple frontend project and do not have many glossaries. What do you think?

ya, if there are not too many uncommon for dev, this is not be needed.

**Comment by SantanaSP** [comment]
If we need it later, we can discuss it at that time. I'll close this issue currently.
