### ISSUE TITLE
Functionality and proposed technologies - Technical solution documentation

### ISSUE THREAD

**Issue by Geoffreyyy** [SparkNFT/SparkLink#161]
## Summary

Functionality and proposed technologies - Technical solution documentation

## Expected Behaviour

Functionality and proposed technologies - Technical solution documentation

technical framework
## Solution

doc or pic

### Alternative

Describe alternatives you've considered

## Roadmap

Maintainer could use this section to record issue roadmap.

**Comment by SantanaSP** [comment]
Fully track in #172.
