### ISSUE TITLE
Communication (network) Interface - Interface documentation

### ISSUE THREAD

**Issue by Geoffreyyy** [SparkNFT/SparkLink#163]
## Summary

Communication (network) Interface - Interface documentation

## Expected Behaviour

Communication (network) Interface - Interface documentation

## Solution

The corresponding description of network request includes the corresponding parameters, fields and return values, as well as the corresponding model attribute and method description of data model layer

**Comment by SantanaSP** [comment]
What's the difference between #162 and this issue?

**Comment by Geoffreyyy** [comment]
> What's the difference between #162 and this issue?

The corresponding description of network request includes the corresponding parameters, fields and return values, as well as the corresponding model attribute and method description of data model layer, so maybe can be merged with #162 ?

**Comment by Geoffreyyy** [comment]
I'm not sure, maybe it could be part of the interface documentation with #162  ? 

btw,I'm not professional in code development, maybe you have good ideas please edit in time

**Comment by SantanaSP** [comment]
I think it's the responsibility of the server repository.

Do you mean this API document? https://github.com/SparkNFT/server/blob/develop/doc/api.apib

**Comment by Geoffreyyy** [comment]
> I think it's the responsibility of the server repository.
> 
> Do you mean this API document? https://github.com/SparkNFT/server/blob/develop/doc/api.apib

oh yes

**Comment by SantanaSP** [comment]
Okay, I'll close this issue.
