### ISSUE TITLE
中间部分国家支持与币种支持重做

### ISSUE THREAD

**Issue by Erreth-Akbe** [SparkNFT/SparkLink#17]
![image](https://user-images.githubusercontent.com/43749085/140600489-d8c302fa-9304-4f54-8222-303b7a110de4.png)
前两张图和最后美刀图片风格不一致，需要重新换图。
不要金币，要币种。
字体需要居中处理，要大写就都大写。
99.9改成99%

**Comment by Geoffreyyy** [comment]
@xiaoyeshi

**Comment by yuhuison** [comment]
Done
