### ISSUE TITLE
We need to use infura or http provider to make the spark page display metadata information and pictures when the user has not connected to the wallet.

### ISSUE THREAD

**Issue by Erreth-Akbe** [SparkNFT/SparkLink#184]
## Summary

We need to use infura or http provider to make the spark page display metadata information and pictures when the user has not connected to the wallet.
And when someone has more than 20 NFT in his collection, the RPC server will response "too many request". We can solve this problem by buying infura service for polygon and ETH, but for BSC I have not find a solution. Maybe BSC RPC server is strong enough for our request.
## Expected Behaviour

Users should be able to see all the collection information when they visit the spark page, even if they are not connected to the wallet. At the same time, on pages such as collection, errors caused by too many requests through the provider should not appear frequently.

## Solution

By using http provider and infura rpc service.

## Additional context

null.

## Roadmap

refactor branch.

**Comment by SantanaSP** [comment]
One single issue should include only one problem / feature request. Please split different problems into the corresponding issues.

**Comment by SantanaSP** [comment]
This issue will be discussed in #187 and finally be traced in #188 .
