### ISSUE TITLE
所有页面的黑色字体，Comming soon等更换为一致

### ISSUE THREAD

**Issue by Erreth-Akbe** [SparkNFT/SparkLink#22]
![image](https://user-images.githubusercontent.com/43749085/140600836-68a09824-4b19-4048-808c-e5f8ce515388.png)
![image](https://user-images.githubusercontent.com/43749085/140600848-6c599c92-d89a-4afc-94ee-f655692dcf78.png)

**Comment by yuhuison** [comment]
Done
