### ISSUE TITLE
网页中英文字段，标点符号需要区分中英文

### ISSUE THREAD

**Issue by Geoffreyyy** [SparkNFT/SparkLink#24]
所有中文字段里面的标点用中文的，英文字段用英语的，尤其是逗号 句号这样的，再检查一遍

![image](https://user-images.githubusercontent.com/92965123/140601537-2b3e4682-f0d8-4dc8-b748-612f09e73efe.png)
![image](https://user-images.githubusercontent.com/92965123/140601541-1abc1e19-9b0d-4b7b-a91a-d198fedea583.png)
![image](https://user-images.githubusercontent.com/92965123/140601549-4bd4effa-5aac-4d0b-bef5-850bac955063.png)

**Comment by yuhuison** [comment]
Done
