### ISSUE TITLE
社交媒体的英语部分 去掉

### ISSUE THREAD

**Issue by Geoffreyyy** [SparkNFT/SparkLink#25]
![image](https://user-images.githubusercontent.com/92965123/140601562-01d646a0-fe52-4e44-aed9-d254cfd90a6d.png)

**Comment by yuhuison** [comment]
Done

**Comment by yuhuison** [comment]
这样的话下面会变得很空泛

**Comment by yuhuison** [comment]
@Geoffreyyy

**Comment by Erreth-Akbe** [comment]
这部分UI需要重做，先做一下调整然后等那边出图

**Comment by Erreth-Akbe** [comment]
@xiaoyeshi
