### ISSUE TITLE
网页默认100%大小的时候 看起来还是太大了，尤其是topbar

### ISSUE THREAD

**Issue by Geoffreyyy** [SparkNFT/SparkLink#27]
![image](https://user-images.githubusercontent.com/92965123/140601975-45352682-fed9-4550-bdbb-4c9f7a838858.png)

**Comment by Geoffreyyy** [comment]
![image](https://user-images.githubusercontent.com/92965123/140602040-9e73761c-4e0e-4301-84ed-5477640f0509.png)
我在看 50%-65%的时候这个topbar看起来还算比较舒服

**Comment by yuhuison** [comment]
字体大小部分正在按照MDUI的标准重新整
