### ISSUE TITLE
我的收藏界面，添加去发布按钮

### ISSUE THREAD

**Issue by Geoffreyyy** [SparkNFT/SparkLink#30]
![image](https://user-images.githubusercontent.com/92965123/140651896-62955f27-99f2-41db-8544-bdb02d648e0e.png)
在我的收藏界面添加去发布按钮，点击后可直接跳转去发布界面

**Comment by Geoffreyyy** [comment]
如果新手进来的话 也可以直接去发布

**Comment by Geoffreyyy** [comment]
按钮添加完成后，把首页的 **SHARE**按钮跳转链接到**我的收藏** 界面

**Comment by yuhuison** [comment]
done
