### ISSUE TITLE
The header has a wrong scrolling behaviour

### ISSUE THREAD

**Issue by SantanaSP** [SparkNFT/SparkLink#68]
## What's going wrong?

See image as follows.

![ezgif-5-d2d22514cf](https://user-images.githubusercontent.com/104019956/165389431-1f134a01-1ed6-491f-9b2f-798051c48049.gif)

## How to reproduce?

Open the index page, and scroll your midden mouse button in the header area.

## Expected behaviour

The header should not be able to scroll.

## Which version?

Branch `refactor`.

**Comment by codeAtNow** [comment]
Which browser will happen this issue,I test on edge and chrome,it will not happen @SantanaSP

**Comment by Erreth-Akbe** [comment]
@codeAtNow chrome, move mouse to the header position, and roll its scoll down side, will see the bug.

**Comment by codeAtNow** [comment]
> @codeAtNow chrome, move mouse to the header position, and roll its scoll down side, will see the bug.

Oh, Yes I see the bug,I will fix it

**Comment by codeAtNow** [comment]
I fix it with add overflow: hidden. #97

**Comment by codeAtNow** [comment]
@Erreth-Akbe @SantanaSP this Issue can be closed
