### ISSUE TITLE
The Chinese translation text seems incomplete

### ISSUE THREAD

**Issue by SantanaSP** [SparkNFT/SparkLink#71]
## What's going wrong?

The Chinese version of the site hasn't been completed yet. There're lots of English text when user changes his language to Chinese.

## How to reproduce?

No need for this issue.

## Expected behaviour

There should not be a dozen of English text in Chinese version.

## Which version?

Branch `refactor`.

**Comment by Erreth-Akbe** [comment]
We will update Chinese version here soon.

**Comment by Erreth-Akbe** [comment]
![image](https://user-images.githubusercontent.com/43749085/166444187-da5ff715-c784-4674-bbed-0fbce59bb0f3.png)
This pictrue need UI/UX assists. @Geoffreyyy

**Comment by Geoffreyyy** [comment]
![Group 364 (2)](https://user-images.githubusercontent.com/92965123/166450079-809d6201-655b-4976-a132-3a47324f83e1.png)
this is the new one need to be translated

**Comment by codeAtNow** [comment]
I have a new PR #95
