### ISSUE TITLE
"royalty price" field in the publishing form should be validated

### ISSUE THREAD

**Issue by SantanaSP** [SparkNFT/SparkLink#73]
## What's going wrong?

The "royalty price" in the publishing form does not get validated currently. When user inpust a value greater than the value appears earlier in "selling price" field no prompt would be given, which will lead to a "contract revert" error at the later stage.

![chrome-capture-2022-3-27 (1)](https://user-images.githubusercontent.com/104019956/165397018-50a7147a-9c9c-4b2c-851d-d5efaec5a17d.gif)

## How to reproduce?

No need for this issue.

## Expected behaviour

After user inputs royalty price, a prompt should be given when the field lost focus.

## Which version?

Branch "refactor".

**Comment by Erreth-Akbe** [comment]
At the same time, the right side needs to add a red option to determine the required items, when the detection of unfilled not allowed to publish.

**Comment by SantanaSP** [comment]
Hello, @Erreth-Akbe . Next time when you add a related issue, please refer to it. For example, in this case you should refer to #141 .

> At the same time, the right side needs to add a red option to determine the required items, when the detection of unfilled not allowed to publish.

**Comment by SantanaSP** [comment]
I'll take over it.
