### ISSUE TITLE
Customers need a mobile version collection page

### ISSUE THREAD

**Issue by SantanaSP** [SparkNFT/SparkLink#86]
## Summary

For path `/collection` we need a mobile version page for our customers, so that they can browser their works using mobile devices.

## Roadmap

- [X] [UI/UX design](https://www.figma.com/file/aOzhPxHjypqHt0v7yTXlGa/sparklink?node-id=1184%3A2716)
- [x] Coding

## Validation

- [x] Customers should be able to check their works in collection view

**Comment by Geoffreyyy** [comment]
under designing.

**Comment by Geoffreyyy** [comment]
done, pls check pages new :https://www.figma.com/file/aOzhPxHjypqHt0v7yTXlGa/sparklink?node-id=1184%3A1568

**Comment by SantanaSP** [comment]
I'll take it.
