### ISSUE TITLE
需要优化的地方

### ISSUE THREAD

**Issue by Geoffreyyy** [SparkNFT/SparkLink#9]
1.![image](https://user-images.githubusercontent.com/92965123/139525920-3ed76390-4955-4763-b727-8fdee656f9e6.png)  页面tab的logo更新

**Comment by Geoffreyyy** [comment]
Logo更新：![image](https://user-images.githubusercontent.com/92965123/139525945-721e702e-9cf2-45bc-b5f9-a6d701022365.png)

**Comment by Geoffreyyy** [comment]
.多语言 英语切换以后要都变英语 有很多地方还是chinese 按钮@yuhuison

**Comment by Geoffreyyy** [comment]
点火按钮鼠标放上去 外框没了 ，并且两个按钮离得太近了
![image](https://user-images.githubusercontent.com/92965123/139526236-d88ddc3e-f4f3-4a9c-a848-243cf090341b.png)
![image](https://user-images.githubusercontent.com/92965123/139526242-521cf4ad-a8b2-4db2-904f-4f489f3ce423.png)

@yuhuison

**Comment by Geoffreyyy** [comment]
完成任务后请close掉

**Comment by Geoffreyyy** [comment]
![image](https://user-images.githubusercontent.com/92965123/139526683-6971f419-2a8b-4c59-99ef-3e966351d74d.png)
鼠标放上去外面框没了 同样的按钮问题

**Comment by Geoffreyyy** [comment]
![image](https://user-images.githubusercontent.com/92965123/139527361-42800d2b-03ac-4c09-a3df-d661acbc14ee.png)
需要新加：1.右上角关闭 2.右下角保存图片
@heacsing

**Comment by Geoffreyyy** [comment]
海报需要新增：
1.右上角关闭
2.右下角保存
![image](https://user-images.githubusercontent.com/92965123/139527475-6f49e050-45b0-4cf8-9239-c5f05ddcd7a7.png)
@heacsing

**Comment by Geoffreyyy** [comment]
页面滑动后，停止滑动在某个位置，顶部bar也需要出现
![image](https://user-images.githubusercontent.com/92965123/139527518-a08bc0e1-da67-4999-b44c-f2b81108a4f7.png)
@yuhuison

**Comment by Geoffreyyy** [comment]
> Logo更新：![image](https://user-images.githubusercontent.com/92965123/139525945-721e702e-9cf2-45bc-b5f9-a6d701022365.png)

@heacsing

**Comment by heacsing** [comment]
> 点火按钮鼠标放上去 外框没了 ，并且两个按钮离得太近了 ![image](https://user-images.githubusercontent.com/92965123/139526236-d88ddc3e-f4f3-4a9c-a848-243cf090341b.png) ![image](https://user-images.githubusercontent.com/92965123/139526242-521cf4ad-a8b2-4db2-904f-4f489f3ce423.png)
> 
> @yuhuison

已修复

**Comment by heacsing** [comment]
> ![image](https://user-images.githubusercontent.com/92965123/139526683-6971f419-2a8b-4c59-99ef-3e966351d74d.png) 鼠标放上去外面框没了 同样的按钮问题

已修复border消失导致的父元素高度坍缩

**Comment by Geoffreyyy** [comment]
新的页面首页下面的两个按钮，目前一个是Learn 一个Earn ，需要把Earn改成Share 。  Learn按钮跳转 Githubbook ，Share按钮跳转到 *去发布* 的界面

跳转推特：https://twitter.com/SparkLink_io
TG电报：https://t.me/SparkLink_io

@yuhuison

**Comment by Geoffreyyy** [comment]
需求：
1.查看作品页面新增 **点火链接分享** 按钮，点击按钮后弹出 “**分享链接复制成功**”弹窗提示，分享链接的格式为：欢迎来到SparkLink查看并购买我的NFT作品：作品URL

2.三个按钮顺序改变 按照图中的位置调整一下

3.分享按钮下面添加一句提示，提示内容为：所有人可通过分享链接或海报进入作品详情页查看以及购买本作品

![image](https://user-images.githubusercontent.com/92965123/139872219-c931c197-ddd6-4422-a6c7-b633c0c80c9a.png)

@heacsing

**Comment by yuhuison** [comment]
已完成
